### ISSUE TITLE
Create manifest files

### ISSUE THREAD

**Issue by Sozialarchiv** [IIIF-Commons/manifesto#50]
Can this library also be used to generate a manifest files? If not is this feature planed?

Something like:

```javascript
const manifest = new Manifest();
manifest.setId(...);
manifest.toJson();
```

**Comment by stephenwf** [comment]
The [Bodleian IIIF Manifest Editor](https://github.com/bodleian/iiif-manifest-editor/blob/a92aa72210892a76ccec620f6000e28e38d828a3/app/reducers/reducers.jsx#L60) uses manifesto in it's editor, but does not use any API to do it. The Manifesto object is just used as a wrapper around the JSON in the manifest and is just updated when the JSON changes.

There's no current APIs in manifesto for updating / editing manifests, although I don't know if it will have that feature in the future.

**Comment by Sozialarchiv** [comment]
Thank you for answer. I already saw the approach of the Manifest editor, but I am looking for a real liberary so that later a migration to the 3.0 API is easy.

I also checked https://github.com/sdellis/tabula-rasa. But I am not sure if it is still under development. I think I will try to contact the autor.

Because our viewer component is using manifesto.js it would be nice to have a related liberary for the server part.

**Comment by edsilv** [comment]
@Sozialarchiv I made this: https://github.com/edsilv/biiif
It will generate Presentation 3 manifests and also supports painting 3D files.
It's a static generator from the file system, so not sure if that fits your use case?

**Comment by Sozialarchiv** [comment]
@edsilv Thank you very much for the link. It looks very interesting. 

But I don't think it fits to our use case: https://github.com/archival-IIIF/server. The server generates manifest files from by a database.

**Comment by edsilv** [comment]
@Sozialarchiv Something I've thought about before is the possibility of using biiif programmatically instead of using the file system. You could potentially pass it a json object model representing files and folders instead of actual files and folders. I quite like the idea of having a generic data model that can be applied for both use cases. e.g.

```
{
  "type": "directory",
  "name": "The Lord of the Rings",
  "description": "The Lord of the Rings Trilogy",
  "attribution": "J. R. R. Tolkien",
  "metadata": {
    "License": "Copyright Tolkien Estate",
    "Author": "J. R. R. Tolkien",
    "Published Date": "29 July 1954"
  },
  "thumb": "path/to/thumb.jpg",
  "children": [
    {
      "type": "directory",
      "name": "The Fellowship of the Ring",
      "metadata": {
        ...
      },
      "thumb": "path/to/thumb.jpg",
      "children": [
        {
          "type": "_directory",
          "name": "Page 1",
          "metadata": {
            ...
          },
          "thumb": "path/to/thumb.jpg",
          "children": [
            {
              "type": "file",
              "name": "path/to/page1.jpg",
              "metadata": {
                ...
              },
            }
          ]
        }
      ]
    }
  ]
}
```

I've used `"type": "_directory"` to symbolise directories named with an underscore.

I suppose if you're doing that though you might as well just write the IIIF manifest in its regular form.

For me, the bigger picture with biiif is to establish that IIIF presentation can be expressed as a simpler more generic files/folders structure. I see this as relatively "future proof" in that the same structure could potentially be serialised in multiple different ways.
